defaults:
  run:
    working-directory: FlutterDotNETWithAPI
    
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore ./FlutterAPI/
      - run: dotnet build ./FlutterAPI/

  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test ./FlutterAPI/

  analyze:
    needs: 
      - build
      - test
    runs-on: ubuntu-20.04
    env:
      SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: dotnet tool install --global dotnet-sonarscanner
      - run: |
          dotnet sonarscanner begin /k:'Flutter-Net_ProjectP2' /o:'flutter-net' /d:sonar.host.url='https://sonarcloud.io/' /d:sonar.login=$SONARCLOUD_TOKEN
          dotnet build ./FlutterAPI/
          dotnet test ./FlutterAPI/
          dotnet sonarscanner end /d:sonar.login=$SONARCLOUD_TOKEN

  pack:
    needs:
      - build
      - test
    runs-on: ubuntu-20.04
    env:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    steps:
      - uses: actions/checkout@v2
      - run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
      - run: docker image build -f ../Dockerfile -t flutterdemo .
      - run: docker image tag flutterdemo flutter2021/projectp2flutter:flutterdemo
      - run: docker push flutter2021/projectp2flutter:flutterdemo
      - run: docker logout

  deploy:
    needs:
      - build
      - test
      - pack
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: FlutterAPI
          images: flutter2021/projectp2flutter:flutterdemo

on: 
  push:
    branches:
      - master